ChatApp/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :chats, only: [:show, :index, :new, :create] do
    resources :messages, only: [:create]
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # messanger
  mount ActionCable.server => "/cable"
end

ChatApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ChatApp/app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :user_one, class_name: "User"
  belongs_to :user_two, class_name: "User"
end

ChatApp/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  after_create :broadcast_message

  def from?(some_user)
    user == some_user
  end

  def broadcast_message
    ActionCable.server.broadcast("chat_#{chat.id}", {
      message_partial: ApplicationController.renderer.render(
        partial: "messages/message",
        locals: { message: self, user_is_messages_author: false }
      ),
      current_user_id: user.id
    })
  end
end

ChatApp/app/models/user.rb
class User < ApplicationRecord

  has_many :messages, dependent: :destroy
  has_many :chats, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

ChatApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

ChatApp/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = Chat.all.where(user_one: current_user).or(Chat.all.where(user_two: current_user))
  end

  def show
    @chat = Chat.includes(messages: :user).find(params[:id])
  end

  def new
    @chat = Chat.new
  end

  def create
    @chat = Chat.new
    @chat.user_one = User.find(params[:chat][:user_one_id])
    @chat.user_two = User.find(params[:chat][:user_two_id])
    @chat.name = {user_one: @chat.user_one, user_two: @chat.user_two}


    if Chat.all.where(user_one_id: current_user.id).exists?(user_two_id: params[:chat][:user_two_id])
      user_chat = Chat.all.where(user_one_id: current_user.id).where(user_two_id: params[:chat][:user_two_id])[0].id
      redirect_to chat_path(user_chat), :flash => { :alert => "Chat already exists" }
    else
      if @chat.save
        redirect_to chat_path(@chat)
      else
        render 'new'
      end
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:name, :user_one, :user_two)
  end
end

ChatApp/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.new(message_params)
    @chat = Chat.find(params[:chat_id])
    @message.chat = @chat
    @message.user = current_user

    if @message.save
      respond_to do |format|
        # format.html { redirect_to chat_path(@chat) }
        format.js
      end
    else
      respond_to do |format|
        # format.html { render "chats/show" }
        format.js
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

ChatApp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

ChatApp/app/helpers/application_helper.rb
module ApplicationHelper
end

ChatApp/app/views/chats/index.html.erb
<div class="container-inbox">
  <%= link_to 'Contact a Person', new_chat_path, class:"btn btn-default contact-btn" %>
  <% if @chats.any? %>
  <% @chats.each do |chat| %>
  <% if chat.messages.any? %>
  <div class="inbox">
    <div class="inbox-body">
      <h3>
        <%= chat.name %>
      </h3>
      <p>
        <%= chat.messages.last.user == current_user ? "✓✓" : "" %>
        <%= chat.messages.last.content %>
      </p>
    </div>
    <div class="inbox-status">
      <p><%= chat.messages.last.created_at.today? ? chat.messages.last.created_at.strftime("%k:%M") : chat.messages.last.created_at.strftime("%A") %></p>
      <h5 class='status'>
        <!--  <%# if !chat.messages.last.read %> message.read gets set to true form the other person, because its not individual for each person so it gets setted true as soon as ones sends it from the chatroom
         ●
         <%# end %> -->
       </h5>
       <p>
        ▷
      </p>
    </div>
    <%= link_to '', chat_path(chat), class:"open-message" %>
  </div>

  <% else %>
  <div class="inbox">
    <div class="inbox-body">
      <h3>
        <%= chat.name %>
      </h3>
      <p><i>No messages</i></p>
    </div>
    <div class="inbox-status">
      <p><%= chat.created_at.today? ? chat.created_at.strftime("%k:%M") : chat.created_at.strftime("%A") %></p>
      <p>
        ▷
      </p>
    </div>
    <%= link_to '', chat_path(chat), class:"open-message" %>
  </div>

  <% end %>
  <% end %>
  <% else %>
  <h3>No Chats</h3>
  <% end %>
</div>

ChatApp/app/views/chats/new.html.erb
<%= simple_form_for @chat do |f| %>
  <p>Contact a person (loged in with <%= current_user.first_name %>)</p>
  <div class="assign-to-person-field">
    <%= f.association :user_two, :include_blank => false, collection: User.where.not(id: current_user), label_method: :first_name %>
    <%= f.input :user_one, :as => :hidden, :input_html => { :value => current_user.id } %>
  </div>
  <%= f.submit 'Contact' %>
<% end %>

ChatApp/app/views/chats/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 chat-body">
      <div class="chat-header">
        <%= link_to 'Back', chats_path, class:"to-inbox-btn" %>
        <h4>
          <%= @chat.name %>
        </h4>
        <!-- avatar -->
      </div>
      <div class="messages">
        <% @chat.messages.each do |message| %>
          <%= render 'messages/message', message: message, user_is_messages_author: message.user == current_user %>
        <% end %>
      </div>
      <div id="suggesstion-box"></div>
      <div id="create-message">
        <%= simple_form_for [ @chat, Message.new ], remote: true do |f| %>
          <%= f.input :content, label: false %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% content_for :after_js do %>

<script>
  scrollLastMessageIntoView();
  App['chat_<%= @chat.id %>'] = App.cable.subscriptions.create(
    { channel: 'ChatsChannel', chat_id: <%= @chat.id %> },
    {
      received: (data) => {
        if (data.current_user_id !== <%= current_user.id %>) {
          const messagesContainer = document.querySelector('.messages');
          messagesContainer.insertAdjacentHTML('beforeend', data.message_partial);
          scrollLastMessageIntoView();
        }
      }
    });
  </script>
  <% end %>

ChatApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
     <%= yield(:after_js) %>
  </body>
</html>

ChatApp/app/views/messages/_message.html.erb
<div class="message <%= user_is_messages_author ? "right" : "" %>">
  avatar
  <p><%= message.content %></p>
</div>

ChatApp/app/views/messages/create.js.erb
//   console.log("before if")
<% if @message.errors.any? %>
  //handle valdiation errors later
  <% else %>
  const messagesContainer = document.querySelector('.messages');
  messagesContainer.insertAdjacentHTML('beforeend', '<%= j render "messages/message", message: @message, user_is_messages_author: true %>')
  const input = document.querySelector('#message_content');
  input.value = '';
  // input.blur();
  scrollLastMessageIntoView();
  <% end %>

ChatApp/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

ChatApp/app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

ChatApp/app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>